"""Writes lib/core/graphql/possible_types.dart: every interface and union of the
schema the app talks to (the live SDL lib/core/graphql/schema.graphql plus the
Hub Market App contract lib/core/graphql/hubapp.graphql), mapped to the object
types that implement it.

graphql_flutter normalises every result into its cache and reads it back. A
fragment on an interface (`fragment F on ProductInterface`) only matches a
`SimpleProduct` when the cache knows SimpleProduct implements ProductInterface;
without `possibleTypes` the fragment's fields silently come back missing.

    python tool/gen_possible_types.py            # write the Dart file
    python tool/gen_possible_types.py --check    # exit 1 when it is stale
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = [
    os.path.join(ROOT, 'lib', 'core', 'graphql', 'schema.graphql'),
    os.path.join(ROOT, 'lib', 'core', 'graphql', 'hubapp.graphql'),
]
OUTPUT = os.path.join(ROOT, 'lib', 'core', 'graphql', 'possible_types.dart')

_BLOCK_STRING = re.compile(r'"""[\s\S]*?"""')
_STRING = re.compile(r'"(?:\\.|[^"\\])*"')
_COMMENT = re.compile(r'#[^\n]*')
_OBJECT = re.compile(
    r'\b(?:extend\s+)?(type|interface)\s+([A-Za-z_]\w*)\s*((?:implements\s+[^{@]*)?)'
)
_UNION = re.compile(r'\b(?:extend\s+)?union\s+([A-Za-z_]\w*)[^=]*=\s*([^{}]*?)(?=\n\s*\n|\n\s*(?:type|interface|union|enum|input|scalar|extend|directive|schema)\b|\Z)')


def _strip(sdl):
    sdl = _BLOCK_STRING.sub('""', sdl)
    sdl = _STRING.sub('""', sdl)
    return _COMMENT.sub('', sdl)


def parse(sdls):
    """(implements, unions): name -> set of interfaces; union -> set of members."""
    implements = {}
    kinds = {}
    unions = {}
    for sdl in sdls:
        text = _strip(sdl)
        for kind, name, clause in _OBJECT.findall(text):
            kinds.setdefault(name, kind)
            names = re.findall(r'[A-Za-z_]\w*', clause.replace('implements', ' ', 1))
            implements.setdefault(name, set()).update(names)
        for name, members in _UNION.findall(text):
            unions.setdefault(name, set()).update(re.findall(r'[A-Za-z_]\w*', members))
    return implements, kinds, unions


def possible_types(sdls):
    implements, kinds, unions = parse(sdls)

    def interfaces_of(name, seen=None):
        seen = set() if seen is None else seen
        for parent in implements.get(name, ()):
            if parent not in seen:
                seen.add(parent)
                interfaces_of(parent, seen)
        return seen

    out = {}
    for name, kind in kinds.items():
        if kind != 'type':
            continue
        for interface in interfaces_of(name):
            out.setdefault(interface, set()).add(name)
    for union, members in unions.items():
        concrete = set()
        for member in members:
            if kinds.get(member) == 'type':
                concrete.add(member)
            else:
                concrete.update(out.get(member, ()))
        out.setdefault(union, set()).update(concrete)
    return {k: v for k, v in out.items() if v}


def render(mapping):
    lines = [
        '// GENERATED by tool/gen_possible_types.py from schema.graphql and',
        '// hubapp.graphql. Do not edit; run `python tool/gen_possible_types.py`.',
        '',
        '/// Every interface and union of the schema, with the object types that',
        '/// implement it: the cache needs it to match a fragment on an interface',
        '/// (`fragment F on ProductInterface`) against a `SimpleProduct`.',
        'const Map<String, Set<String>> kPossibleTypes = <String, Set<String>>{',
    ]
    for name in sorted(mapping):
        members = ', '.join("'%s'" % m for m in sorted(mapping[name]))
        entry = "  '%s': <String>{%s}," % (name, members)
        if len(entry) <= 80:
            lines.append(entry)
        else:
            lines.append("  '%s': <String>{" % name)
            for member in sorted(mapping[name]):
                lines.append("    '%s'," % member)
            lines.append('  },')
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main(argv):
    sdls = []
    for path in SOURCES:
        with io.open(path, encoding='utf-8') as fh:
            sdls.append(fh.read())
    text = render(possible_types(sdls))
    if '--check' in argv:
        try:
            with io.open(OUTPUT, encoding='utf-8') as fh:
                current = fh.read().replace('\r\n', '\n')
        except FileNotFoundError:
            current = ''
        if current != text:
            print('possible_types.dart is stale: run python tool/gen_possible_types.py')
            return 1
        print('possible_types.dart is up to date')
        return 0
    with io.open(OUTPUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %s (%d abstract types)' % (os.path.relpath(OUTPUT, ROOT), text.count("': <String>{")))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
